typedef struct {
    const char* bot_id;
    const char* expected_actor;
} SP3ActorMapping;

static const SP3ActorMapping g_sp3_actor_table[] = {
    { "acidstorm_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "arcee_gs_deluxe2014", "Arcee_GS_Deluxe2014" },
    { "barricade_cin_dotm", "Barricade_Cin_DOTM" },
    { "bitstream_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "blaster_gs_leader2016", "Blaster_GS_Leader2016" },
    { "bludgeon_gs_rd20", "Bludgeon_GS_RD20" },
    { "bonecrusher_cin_rotf", "Bonecrusher_Cin_ROTF" },
    { "breakdown_gs", "Sideswipe_GS" },
    { "bumblebee_cin_dotm", "Bumblebee_Cin_DOTM" },
    { "bumblebee_gs_kabam", "Bumblebee_GS_Kabam" },
    { "cheetor_bw_transmetal", "Cheetor_BW_Transmetal" },
    { "chromia_gs_kabam", "Chromia_GS_Kabam" },
    { "cliffjumper_gs_kabam", "Cliffjumper_GS_Kabam" },
    { "cyclonus_gs_uw06", "Cyclonus_GS_UW06" },
    { "deadend_gs_deluxe2015", "Deadend_GS_Deluxe2015" },
    { "dinobot_bw_kabam", "Dinobot_BW_Kabam" },
    { "dirge_gs_deluxe2008", "Dirge_GS_Deluxe2008" },
    { "dragstrip_gs_deluxe2016", "Mirage_GS_Deluxe2016" },
    { "drift_cin_aoe", "Drift_Cin_AOE" },
    { "fte_optimus_gs_t3", "OptimusPrime_GS_V" },
    { "fte_stars_gs_t3", "Starscream_GS" },
    { "galvatron_gs_voyager2016", "Galvatron_GS_Voyager2016" },
    { "grimlock_gs_mp08", "Grimlock_GS_MP08" },
    { "grindor_cin_rotf", "Grindor_Cin_ROTF" },
    { "hotlink_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "hotrod_cin_tlk", "HotRod_Cin_TLK" },
    { "hound_cin_tlk", "Hound_Cin_TLK" },
    { "ionstorm_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "ironhide_cin_rotf", "IronHide_Cin_ROTF" },
    { "ironhide_gs_kabam", "Ironhide_GS_Kabam" },
    { "jazz_gs_twm05", "Jazz_GS_TWM05" },
    { "jetfire_gs_leader2014", "Jetfire_GS_Leader2014" },
    { "kickback_gs_kabam", "Kickback_GS_Kabam" },
    { "lifeline_gs_deluxe2014", "Lifeline_GS_Deluxe2014" },
    { "megatron_cin_rotf", "Megatron_Cin_ROTF" },
    { "megatron_gs_leader2015", "Megatron_GS_Leader2015" },
    { "megatronus_gs_kabam", "Megatronus_GS_Kabam" },
    { "mirage_gs_deluxe2016", "Mirage_GS_Deluxe2016" },
    { "mixmaster_cin_rotf", "Mixmaster_Cin_ROTF" },
    { "motormaster_gs_voyager2015", "Motormaster_GS_Voyager2015" },
    { "necrotronus_gs_kabam", "Necrotronus_GS_Kabam" },
    { "nemesisprime_gs_voyager2015", "NemesisPrime_GS_Voyager2015" },
    { "novastorm_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "optimusprimal_bw_mp32", "OptimusPrimal_BW_MP32" },
    { "optimusprime_cin_tf", "OptimusPrime_Cin_TF" },
    { "optimusprime_gs_v", "OptimusPrime_GS_V" },
    { "optimusprime_sg_voyager2015", "NemesisPrime_GS_Voyager2015" },
    { "prowl_gs_deluxe2016", "Prowl_GS_Deluxe2016" },
    { "ramjet_gs_deluxe2008", "Ramjet_GS_Deluxe2008" },
    { "ratchet_gs_kabam", "Ratchet_GS_Kabam" },
    { "rhinox_gs_voyager2014", "Rhinox_GS_Voyager2014" },
    { "rodimusprime_gs_mp09", "RodimusPrime_GS_MP09" },
    { "scorponok_bw_kabam", "Scorponok_BW_Kabam" },
    { "sharkticon_gs_brawler", "Sharkticon_GS_Brawler" },
    { "sharkticon_gs_demolition", "Sharkticon_GS_Demolition" },
    { "sharkticon_gs_kabam", "Sharkticon_GS_Kabam" },
    { "sharkticon_gs_scout", "Sharkticon_GS_Scout" },
    { "sharkticon_gs_tactician", "Sharkticon_GS_Tactician" },
    { "sharkticon_gs_tech", "Sharkticon_GS_Tech" },
    { "sharkticon_gs_warrior", "Sharkticon_GS_Warrior" },
    { "shockwave_gs", "Shockwave_GS" },
    { "sideswipe_gs", "Sideswipe_GS" },
    { "skywarp_gs_leader2015", "Skywarp_GS_Leader2015" },
    { "slipstream_gs", "Slipstream_GS" },
    { "soundblaster_gs_mp13b", "Soundblaster_GS_MP13B" },
    { "soundwave_gs", "Soundwave_GS" },
    { "starsaber_gs_leader2014", "Jetfire_GS_Leader2014" },
    { "starscream_ghost_gs", "Thundercracker_GS_leader2015" },
    { "starscream_gs", "Starscream_GS" },
    { "sunstorm_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "sunstreaker_gs_deluxe2008", "Sunstreaker_GS_Deluxe2008" },
    { "tantrum_gs_kabam", "Tantrum_GS_Kabam" },
    { "test_verify_dirge", "Dirge_GS_Deluxe2008" },
    { "thrust_gs_deluxe2008", "Dirge_GS_Deluxe2008" },
    { "thundercracker_gs_leader2015", "Thundercracker_GS_leader2015" },
    { "ultramagnus_gs_leader", "UltraMagnus_GS_Leader" },
    { "ultramagnus_sg_leader", "UltraMagnus_GS_Leader" },
    { "waspinator_gs_deluxe", "Waspinator_GS_Deluxe" },
    { "wheeljack_gs_mp20", "Wheeljack_GS_MP20" },
    { "wildrider_gs_deluxe2016", "Prowl_GS_Deluxe2016" },
    { "windblade_gs", "WindBlade_GS" },
    { NULL, NULL }
};

static const char* sp3_lookup_expected_actor(const char* bot_id) {
    if (!bot_id || !bot_id[0]) return NULL;
    for (int i = 0; g_sp3_actor_table[i].bot_id != NULL; i++) {
        if (strcasecmp(bot_id, g_sp3_actor_table[i].bot_id) == 0) {
            return g_sp3_actor_table[i].expected_actor;
        }
    }
    return NULL;
}
